export * from './actionPointEndpoint.service';
import { ActionPointEndpointService } from './actionPointEndpoint.service';
export * from './memberEndpoint.service';
import { MemberEndpointService } from './memberEndpoint.service';
export * from './comment-endpoint.service';
import { CommentEndpointService } from './comment-endpoint.service';
export * from './taskEndpoint.service';
import { TaskEndpointService } from './taskEndpoint.service';
export * from './workingGroupEndpoint.service';
import { WorkingGroupEndpointService } from './workingGroupEndpoint.service';
export const APIS = [ActionPointEndpointService, MemberEndpointService, CommentEndpointService, TaskEndpointService, WorkingGroupEndpointService];
